# -*- coding: utf-8 -*-
"""forecasting mini project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwUvOciam6SdhfhG5s1HI3RpI_KvMN2P
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

a=pd.read_csv("//content/AirPassengers.csv")

a

print(a.head())

print(a.tail())

a["Month"]=pd.to_datetime(a["Month"])

a=a.set_index("Month")
print(a.head())

print(a.isnull().sum())

print(a.duplicated().sum())

a=a.drop_duplicates()

print(a.duplicated().sum())

plt.figure(figsize=(12,5))
plt.plot(a['#Passengers'])
plt.title("Air passengers ")
plt.xlabel("Month ")
plt.ylabel("Number of Passengers")
plt.show()

train_size = int(len(a)*0.8)
train = a.iloc[:train_size]
test = a.iloc[train_size:]
print("Training:",len(train))
print("Testing:",len(test))

